import React from 'react';
import { AlertOctagon, Scale, ShieldX, Info, FileWarning } from 'lucide-react';
import { DocumentWatermark, CornerMotif, SectionHeader, DocCard, TechLabel, ClauseFrame } from './DocHelpers';

export const DisclaimerContent = () => (
  <div className="space-y-0 pb-40 max-w-6xl mx-auto selection:bg-red-500/20 relative">
    <DocumentWatermark text="VIGIL LEGAL REGISTRY" />
    
    <SectionHeader 
      id="DOC: VIG-DISC-2026.01"
      category="Strategic Legal Unit"
      title="Definitive Disclaimer."
      subtitle="Liability boundaries and operational risk disclosure"
      colorClass="text-red-500"
      bgGlow="bg-red-600/10"
    />

    <div className="space-y-12 px-6 md:px-12 relative z-10">
       
       <DocCard border="zinc">
          <div className="flex items-center gap-4 border-b border-zinc-900 pb-6 mb-8">
             <Scale className="w-6 h-6 text-zinc-600" />
             <h3 className="text-2xl font-black text-white italic uppercase tracking-tight">General Information and Scope</h3>
          </div>
          <div className="space-y-6 text-zinc-400 text-lg leading-relaxed font-medium">
             <p>VIGIL is a browser-based security extension and companion software designed to assist users in identifying potential risks, anomalies, and deceptive patterns during digital interactions, particularly those involving decentralized applications, blockchain interfaces, wallet connections, smart contract prompts, and transaction flows. VIGIL operates at the human interaction layer by providing contextual warnings, visual indicators, and heuristic-based signals intended to improve user awareness.</p>
             <p className="bg-zinc-950 border border-zinc-900 p-6 rounded-2xl border-l-4 border-l-red-600 font-bold text-white">VIGIL does not function as a transaction executor, validator, custodian, wallet, exchange, broker, or financial intermediary. All actions taken within a browser, wallet, or decentralized application remain entirely under the user’s control.</p>
             <p className="italic underline decoration-zinc-800 underline-offset-8">This Disclaimer governs the use of VIGIL in all forms, including but not limited to browser extensions, dashboards, alert systems, documentation, user interfaces, APIs (if any), experimental features, and research outputs. By installing, accessing, or using VIGIL, the user acknowledges and agrees to the limitations, exclusions, and responsibilities described herein.</p>
          </div>
       </DocCard>

       <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
         <DocCard border="cyan">
            <h3 className="text-xl font-black text-white italic uppercase tracking-tight mb-6">No Professional Advice</h3>
            <div className="space-y-4 text-sm text-zinc-500 font-medium leading-relaxed">
               <p>VIGIL does not provide financial advice, investment advice, trading advice, legal advice, tax advice, or any form of professional advisory service.</p>
               <p>Any alerts, warnings, labels, classifications, risk indicators, or informational messages generated by VIGIL are purely informational and educational in nature. They are not recommendations to approve, reject, execute, cancel, delay, or modify any transaction or interaction.</p>
            </div>
         </DocCard>

         <DocCard border="red">
            <h3 className="text-xl font-black text-white italic uppercase tracking-tight mb-6">No Guarantee of Security</h3>
            <div className="space-y-4 text-sm text-zinc-500 font-medium leading-relaxed">
               <p>While VIGIL is designed to detect and signal known patterns of deception, including address manipulation and visual spoofing, no security system is infallible.</p>
               <p className="text-red-500 font-black uppercase tracking-widest text-[10px]">Absence of a warning should never be interpreted as confirmation of safety.</p>
            </div>
         </DocCard>
       </div>

       <DocCard border="emerald" glow>
          <h3 className="text-2xl font-black text-white italic uppercase tracking-tight mb-8">Human Judgment Remains Essential</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-12">
             <div className="space-y-6">
                <TechLabel text="CORE PHILOSOPHY" color="emerald" />
                <ul className="space-y-4 text-zinc-400 text-sm italic font-medium">
                   <li>• Security failures often arise from human misinterpretation</li>
                   <li>• Context, intent, and judgment cannot be fully automated</li>
                   <li>• Users must remain attentive, skeptical, and informed</li>
                </ul>
             </div>
             <div className="space-y-6">
                <TechLabel text="USER VERIFICATION" color="emerald" />
                <ul className="space-y-4 text-zinc-400 text-sm italic font-medium">
                   <li>• Recipient addresses</li>
                   <li>• Contract permissions</li>
                   <li>• Token identities</li>
                   <li>• Website authenticity</li>
                </ul>
             </div>
          </div>
       </DocCard>

       <DocCard border="red">
          <div className="flex items-center gap-4 mb-10 border-b border-red-900/20 pb-6">
             <ShieldX className="w-8 h-8 text-red-600" />
             <h3 className="text-3xl font-black text-white italic uppercase tracking-tight">Limitation of Liability</h3>
          </div>
          <div className="space-y-8">
             <p className="text-xl text-zinc-300 font-bold uppercase tracking-tight">To the maximum extent permitted, VIGIL and its contributors shall not be liable for any direct, indirect, incidental, consequential, special, exemplary, or punitive damages, including but not limited to:</p>
             <div className="grid grid-cols-2 md:grid-cols-3 gap-6">
                {["Financial loss", "Asset loss", "Missed opportunities", "Reputational harm", "Data loss", "System compromise"].map(item => (
                  <div key={item} className="flex items-center gap-4 p-4 bg-zinc-950 border border-zinc-900 rounded-xl group/item">
                     <TechLabel text="EXCLUDED" color="red" />
                     <span className="text-sm font-black text-zinc-500 uppercase tracking-widest group-hover/item:text-white transition-colors">{item}</span>
                  </div>
                ))}
             </div>
             <p className="text-sm text-zinc-500 font-medium italic border-l-2 border-red-900/30 pl-6">This limitation applies regardless of the theory of liability and even if VIGIL has been advised of the possibility of such damages.</p>
          </div>
       </DocCard>

       <DocCard border="zinc">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-12">
             <div className="space-y-6">
                <h4 className="text-xs font-black text-white uppercase tracking-widest border-b border-zinc-900 pb-3">No Warranty; "As-Is" Provision</h4>
                <p className="text-xs text-zinc-500 leading-relaxed uppercase tracking-tight font-bold">VIGIL is provided on an “as-is” and “as-available” basis, without warranties of any kind. Use of VIGIL is entirely at the user’s own risk.</p>
             </div>
             <div className="space-y-6">
                <h4 className="text-xs font-black text-white uppercase tracking-widest border-b border-zinc-900 pb-3">Final Acknowledgment</h4>
                <p className="text-xs text-zinc-500 leading-relaxed italic">By installing, accessing, or using VIGIL, the user confirms that they have read, understood, and agreed to this Disclaimer in its entirety.</p>
             </div>
          </div>
       </DocCard>

       <div className="pt-24 text-center space-y-8">
          <div className="h-[2px] w-32 bg-zinc-900 mx-auto" />
          <h3 className="text-4xl font-black text-white italic uppercase tracking-widest">End of Disclaimer</h3>
          <p className="text-[10px] font-black text-zinc-700 uppercase tracking-widest">Registry Reference: VIG-LEGAL-CORE-A1</p>
       </div>
    </div>
  </div>
);